version: "3.9"
services:
  www: # php at apache container
    image: php_container #php:8.1.1-apache    
    volumes:
      - ./php_container:/var/www/html      
    ports:
      - 80:80
      - 443:443
      - 8080:80      
    depends_on:
      - mongodb 
    restart: always
  mongodb:
    image: mongo:latest    
    ports:
      - "27017:27017"
    environment:      
      MONGO_INITDB_ROOT_USERNAME: ''
      MONGO_INITDB_ROOT_PASSWORD: ''
    volumes:
      - ./mongodb-data:/data/db
    restart: always
  mongodb-compass:
    image: mongo-express:latest    
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb      
    depends_on:
      - mongodb
    restart: always